### ISSUE TITLE
new sidebarBehaviorHome param

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#19]
Not sure about this - what do people think?

Basically the homepage looks better without the side nav. But the sidenav is really important on ALL other pages. What I'm wondering about is whether there is a better sidebarBehavior for just the homepage. sidebarBehaviorHome param = 1|2|3|4|5|6|7 

This possible? If it is I wonder if this should be pushed to the upstream project..

**Comment by hosseinzoda** [comment]
We have already made so many changes on this theme. And i think it should be that way, Otherwise adding general features to the theme is going to be more time consuming task.
I can simply change this file https://github.com/openassistive/hugo-tranquilpeak-theme/blob/master/layouts/index.html to modify sidebar for homepage.
What do you think?

**Comment by willwade** [comment]
Yeah. Fine with me :)
